### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by ghost** [macroecology/paleoMap#5]
Hi, I got this error, wouldn't be able to install paleoMap:
Downloading GitHub repo macroecology/paleoMap@master
from URL https://api.github.com/repos/macroecology/paleoMap/zipball/master
Installing paleoMap
"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Uzma/AppData/Local/Temp/RtmpgtpuW8/devtools3b3c3ccf5416/macroecology-paleoMap-050b84f"  \
  --library="C:/Users/Uzma/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'paleoMap' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
Warning: C:/Users/Uzma/AppData/Local/Temp/RtmpgtpuW8/devtools3b3c3ccf5416/macroecology-paleoMap-050b84f/man/paleoMap.Rd:1: All text must be in a section
Error : C:/Users/Uzma/AppData/Local/Temp/RtmpgtpuW8/devtools3b3c3ccf5416/macroecology-paleoMap-050b84f/man/paleoMap.Rd: Sections \title, and \name must exist and be unique in Rd files
ERROR: installing Rd objects failed for package 'paleoMap'
* removing 'C:/Users/Uzma/Documents/R/win-library/3.3/paleoMap'
Installation failed: Command failed (1)

Best,
Uzma

**Comment by sonjaleo** [comment]
@UzmaSalam  Thank you very much for telling about the issue. 
We are currently working on the package and changed a lot of things. Now we are going to have an external data package where the maps are stored.
A working version should be online again next week. 
We are happy if you are going to use the upcomming version and telling us about your issues.
best regards, 
Sonja

**Comment by ghost** [comment]
Yes I was able to install the package somehow after many tries. It worked as well.
Thank you,
Best,
Uzma
