### ISSUE TITLE
map of late Miocene

### ISSUE THREAD

**Issue by ghost** [macroecology/paleoMap#6]
Hi, I have a question it is possible to make a map of "young Oligocene Late Miocene" of age 35-10 Mya?
Thank you!
Best,
Uz

**Comment by sonjaleo** [comment]
Hi Uz,
No I'm sorry we don't provide such a map in our package.
If you can get such a map from somewhere else you could try to import it as SpatialPolygonsDataFrame in R and then use it as input for the functions of the package.
Best,
Sonja

 

 

 

-----Ursprüngliche Mitteilung----- 
Von: Uzma <notifications@github.com>
An: macroecology/paleoMap <paleoMap@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Verschickt: Mi, 25. Okt 2017 16:32
Betreff: [macroecology/paleoMap] map of late Miocene (#6)



Hi, I have a question it is possible to make a map of "young Oligocene Late Miocene" of age 35-10 Mya?
Thank you!
Best,
Uz
